In [1]:
import torch

# Data Manipulation

## Getting Started

In [3]:
# arange
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
# number of elements
x.numel()

12

In [5]:
# shape
x.shape

torch.Size([12])

In [6]:
# reshape
y = x.reshape((3,4))
y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
# zeros
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# ones
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# random normal
torch.randn((3,4))

tensor([[-0.6887,  0.3409,  0.6780, -0.6138],
        [ 0.0298,  0.5234, -0.9121, -1.9939],
        [ 0.2722, -0.7886, -0.1966, -0.1834]])

In [11]:
# create tensor
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
x

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Indexing and Slicing

In [21]:
x = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [22]:
x[-1]

tensor([5., 6.])

In [23]:
x[1:3]

tensor([[3., 4.],
        [5., 6.]])

In [24]:
# write element
x[1, 1] = 10
x

tensor([[ 1.,  2.],
        [ 3., 10.],
        [ 5.,  6.]])

In [25]:
# assign multiple elements
x[:2, 1] = 99
x

tensor([[ 1., 99.],
        [ 3., 99.],
        [ 5.,  6.]])

## Operations